name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

jobs:
  foundry:
    name: Foundry
    permissions:
      contents: read
    uses: aoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoa/eternalist-foundry/.github/workflows/pipeline.yml@1107101839dc640f19252f7c734f4c8b713310e2

  release:
    name: Release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: foundry
    permissions:
      contents: write
    uses: aoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoa/eternalist-foundry/.github/workflows/publish.yml@1107101839dc640f19252f7c734f4c8b713310e2
