name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

jobs:
  foundry:
    uses: ./.github/workflows/pipeline.yml
    with:
      publish: ${{ startsWith(github.ref, 'refs/tags/v') }}
